import type { Metadata } from "next";
import { Raleway, IBM_Plex_Sans, Source_Sans_3, Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import { Toaster } from "sonner";

const sourceSans3Heading = Source_Sans_3({ subsets: ['latin'], variable: '--font-heading' });

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html
      lang="en"
      className={cn("h-full antialiased", "font-sans", inter.variable, sourceSans3Heading.variable)}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <Toaster position="top-right" />
        {/* navbar */}
        {/* <Navbar /> */}
        {children}
        {/* footer */}
      </body>
    </html>
  );
}
